version: '3.4'

services:
  cleancodeochtestbarkod-labb4:
    image: ${DOCKER_REGISTRY-}cleancodeochtestbarkodlabb4
    build:
      context: .
      dockerfile: CleanCodeOchTestbarKod-Labb4/Dockerfile
    ports:
      - "80:80"

  calculatorapi:
    image: ${DOCKER_REGISTRY-}calculatorapi
    build:
      context: .
      dockerfile: CalculatorAPI/Dockerfile


  magicthevotingapi:
    image: ${DOCKER_REGISTRY-}magicthevotingapi
    build:
      context: .
      dockerfile: MagicTheVotingAPI/Dockerfile

